# name: Build and Deploy

# on:
#   push:
#     branches: ['main']

# jobs:
#   build_deploy:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@master
#       - name: Build
#         uses: TartanLlama/actions-eleventy@master
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           publish_dir: _site 
#           publish_branch: gh-pages
#           deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}